# Generated by Django 5.1.1 on 2024-10-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_todo_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
